### mengambil data semua data penjualan
GET http://localhost:3000/api/penjualan

### mengambil data penjualan berdasarkan id
GET http://localhost:3000/api/penjualan/1

### membuat data penjualan
POST http://localhost:3000/api/penjualan
Content-Type: application/json

{
  "tgl_transaksi":"2023-01-01T00:00:00.000Z",
  "keterangan":"di bayar dengan menggunakan atm",
  "id_barang":1,

  "tgl_bayar": "2023-01-01T00:00:00.000Z",
  "total_bayar":200,

  "nama_pembeli":"febrian",
  "alamat":"jln. Semarang",
  "no_hp":"+62 123 123 123"
}

### mengubah data penjualan berdasarkan id
PUT http://localhost:3000/api/penjualan/1
Content-Type: application/json

{
  "tgl_transaksi":"2023-01-01T00:00:00.000Z",
  "keterangan":"di bayar dengan menggunakan atm update",
  "id_barang":1,

  "tgl_bayar": "2023-01-01T00:00:00.000Z",
  "total_bayar":200,

  "nama_pembeli":"febrian",
  "alamat":"jln. jetis semarang",
  "no_hp":"+62 123 123 123"
}

### Menghapus data penjualan berdasarkan id
DELETE  http://localhost:3000/api/penjualan/1
