### Mengambil data semua data produk
GET http://localhost:3000/api/produk

### Mengambil data produk berdasarkan id
GET http://localhost:3000/api/produk/1

### Membuat data produk
POST http://localhost:3000/api/produk
Content-Type: application/json

{
  "nama_supplier": "swallows",
  "alamat": "jln. ungaran rayas",
  "no_telp": "+64 123 123 12344",
  "nama_barang": "sandal",
  "harga": 2000,
  "stok": 100
}

### Mengubah data produk berdasarkan id
 PUT http://localhost:3000/api/produk/2
Content-Type: application/json

{
  "nama_supplier": "swallow",
  "alamat": "jln. ungaran raya",
  "no_telp": "+64 123 123 1234",
  "nama_barang": "sandal",
  "harga": 2000,
  "stok": 100
}

### Menghapus data produk berdasarkan id
 DELETE http://localhost:3000/api/produk/14
